const GS_NOTIFICATION_METERS_START_DAY_OF_MONTH = 20;
const GS_NOTIFICATION_METERS_EXPRESSION = '0 12 20-31 * *';

export {
  GS_NOTIFICATION_METERS_EXPRESSION,
  GS_NOTIFICATION_METERS_START_DAY_OF_MONTH,
};
